string = input()
string = string.replace("c=", "1")
string = string.replace("c-", "2")
string = string.replace("dz=", "3")
string = string.replace("d-", "4")
string = string.replace("lj", "5")
string = string.replace("nj", "6")
string = string.replace("s=", "7")
string = string.replace("z=", "8")
print(len(string))
